- public  $finder = "null"
- public  $parser = "null"
- public  $render = "null"
- public string $inDir = "null"
- Finder()
- Render()
- ParserFactory()
- PropertiesFinder()
- ClassesFinder()
- MethodsFinder()
- RecursiveIteratorIterator()
- RecursiveDirectoryIterator()
- RegexIterator()
- __construct( $inDir = ): 
- generate( $toDir = ): 
- getFiles( $inDir = ): 
